# Production environment configuration

database:
  path: "${DB_PATH}"
  max_connections: 50
  timeout_seconds: 60

twitch:
  client_id: "${TWITCH_CLIENT_ID}"
  client_secret: "${TWITCH_CLIENT_SECRET}"
  check_interval_secs: 300

discord:
  streamers:
    example_streamer: "${DISCORD_WEBHOOK_URL}"
  rate_limit: 10
  username: "TwitchClipBot"

server:
  host: "0.0.0.0"
  port: 80
  read_timeout_seconds: 30
  write_timeout_seconds: 30

metrics:
  enabled: true
  namespace: "twitchclipsearch"
  endpoint: "/metrics"

logging:
  level: "info"
  format: "json"
  output: "${LOG_OUTPUT}"