apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitchclipsearch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: twitchclipsearch
  template:
    metadata:
      labels:
        app: twitchclipsearch
    spec:
      containers:
      - name: twitchclipsearch
        image: twitchclipsearch:latest
        ports:
        - containerPort: 8080
        env:
        - name: GO_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GO_ENV
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20