apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

bases:
  - ../../base

resources:
  - namespace.yaml

configMapGenerator:
  - name: app-config
    literals:
      - GO_ENV=production

patches:
  - path: deployment-patch.yaml

images:
  - name: twitchclipsearch
    newName: ghcr.io/0x0060/twitchclipsearch
    newTag: latest

replicas:
  - name: twitchclipsearch
    count: 3